export const mock = {
  product1: {
    id: '1',
    title: 'iPhone 9',
    description: 'An apple mobile which is nothing like apple',
    price: 10,
    discountPercentage: 10,
    rating: 4.69,
    stock: 94,
    brand: 'Apple',
    category: 'smartphones',
    thumbnail: '...',
    images: ['...', '...', '...'],
  },
  product2: {
    id: '2',
    title: 'notIPhone 9',
    description: 'An apple mobile which is nothing like apple',
    price: 20,
    discountPercentage: 20,
    rating: 4.69,
    stock: 35,
    brand: 'Apple',
    category: 'smartphones',
    thumbnail: '...',
    images: ['...', '...', '...'],
  },
  product3: {
    id: '3',
    title: 'alsoNotIPhone 9',
    description: 'An apple mobile which is nothing like apple',
    price: 30,
    discountPercentage: 30,
    rating: 4.69,
    stock: 20,
    brand: 'Apple',
    category: 'smartphones',
    thumbnail: '...',
    images: ['...', '...', '...'],
  },
};